server:
   servlet:
      context-path: /
   port: 5000
spring:
   profiles:
      active: '@spring.profiles.active@'
   datasource:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:appdb}?useSSL=false
      username: ${MYSQL_USERNAME:appdbusername}
      password: ${MYSQL_PASSWORD:appdbpassword}
   jpa:
      hibernate:
         ddl-auto: create
      properties:
         hibernate:
         dialect: org.hibernate.dialect.MySQL8Dialect
   application:
      name: app
#   main:
#      banner-mode: 'off'
