server:
   servlet:
      context-path: /app
   port: 8090
spring:
   application:
      name: app
   datasource:
      url: jdbc:mysql://localhost:3306/jdbc?useSSL=false
      username: root
      password: root
   main:
      banner-mode: 'off'
logging:
   level:
      org:
         springframework: ERROR