server:
   servlet:
      context-path: /app
   port: 8090
spring:
   profiles:
      active: '@spring.profiles.active@'
   datasource:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DB:aws_eb_db}?
      username: ${MYSQL_USERNAME:root}
      password: ${MYSQL_PASSWORD:root}
   jpa:
      hibernate:
         ddl-auto: create
      properties:
         hibernate:
         dialect: org.hibernate.dialect.MySQL8Dialect
   application:
      name: app
#   main:
#      banner-mode: 'off'
